site_name: Glutton Documentation
version: 1.0
nav:
  - Introduction: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Deployment: deployment.md
theme:
  name: readthedocs

